### ISSUE TITLE
console apps use nonexistent dmsh.cli

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/dmsh#47]
setup.cfg contains configuration for console apps
```
[options.entry_points]
console_scripts =
    dmsh-image = dmsh.cli:image
    dmsh-poly = dmsh.cli:poly
```

This causes /usr/bin/dmsh-image and /usr/bin/dmsh-poly to be created.  But running the apps fails, since there is no `dmsh.cli`,
```
 dmsh-image 
Traceback (most recent call last):
  File "/usr/bin/dmsh-image", line 33, in <module>
    sys.exit(load_entry_point('dmsh==0.2.3', 'console_scripts', 'dmsh-image')())
  File "/usr/bin/dmsh-image", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dmsh.cli'
```

Should these `console_scripts` entries be removed?
Since there is no dmsh.cli, I guess the entries should be removed.

**Comment by nschloe** [comment]
> Should these console_scripts entries be removed?

Absolutely. Copy-and-paste error. I'll take care of it right away.
